version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      next-react:
        patterns:
          - next
          - eslint-config-next
          - react
          - react-dom
      prisma:
        patterns:
          - prisma
          - "@prisma/*"
      serwist:
        patterns:
          - serwist
          - "@serwist/*"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
