package me.gordon.gemsteps

// Stable IDs, content, defaults and order match the iOS catalog.
object Catalog {
    val templates = listOf(
        Item("seed-task-make-bed", "整理床铺", "Make my bed", "🛏️", 2, false, true, true, null, 0),
        Item("seed-task-brush", "早上刷牙", "Brush my teeth in the morning", "🪥", 2, false, false, true, null, 1),
        Item("seed-task-face", "洗脸", "Wash my face", "🚿", 1, false, false, true, "face_wash", 2),
        Item("seed-task-clothes", "穿好衣服", "Get dressed", "👕", 1, false, true, true, null, 3),
        Item("seed-task-pack-bag", "整理书包", "Pack my school bag", "🎒", 2, false, false, true, null, 4),
        Item("seed-task-shoes", "穿好鞋子", "Put on my shoes", "👟", 1, false, true, true, null, 5),
        Item("seed-task-say-goodbye", "离开时说再见", "Say goodbye when leaving", "🙋", 1, false, false, true, null, 6),
        Item("seed-task-buckle-up", "配合系好安全带", "Cooperate with buckling up", "🚗", 1, false, false, true, "child_seat_harness", 7),
        Item("seed-task-say-hello", "主动打招呼", "Say hello", "👋", 1, false, false, true, null, 8),
        Item("seed-task-put-shoes-away", "回家把鞋放好", "Put away my shoes when I get home", "👟", 1, false, false, true, null, 9),
        Item("seed-task-handwash", "洗手", "Wash my hands", "🧼", 1, false, true, true, "handwash_faucet", 10),
        Item("seed-task-homework", "完成约定的作业", "Finish the agreed homework", "📝", 3, false, false, true, null, 11),
        Item("seed-task-writing", "练习书写", "Practice handwriting", "✍️", 3, false, false, true, null, 12),
        Item("seed-task-math", "练习数学", "Practice math", "🧮", 3, false, false, true, null, 13),
        Item("seed-task-words", "练习单词", "Practice words", "🔤", 3, false, false, true, null, 14),
        Item("seed-task-instrument", "练习乐器", "Practice an instrument", "🎵", 3, false, false, true, null, 15),
        Item("seed-task-extracurricular", "完成课外练习", "Complete extracurricular practice", "🎯", 3, false, false, true, null, 16),
        Item("seed-task-tidy-toys", "收好玩具", "Put away my toys", "🧸", 2, false, true, true, null, 17),
        Item("seed-task-put-things-away", "把用过的物品放回原处", "Put things back where they belong", "📦", 1, false, false, true, null, 18),
        Item("seed-task-set-table", "帮忙摆餐具", "Help set the table", "🍽️", 2, false, false, true, null, 19),
        Item("seed-task-clear-dishes", "饭后收好自己的餐具", "Clear my dishes after a meal", "🥣", 2, false, false, true, null, 20),
        Item("seed-task-wipe-table", "擦桌子", "Wipe the table", "🧽", 2, false, false, true, null, 21),
        Item("seed-task-pyjamas", "换好睡衣", "Put on my pajamas", "👕", 1, false, false, true, null, 22),
        Item("seed-task-laundry-basket", "把脏衣服放进洗衣篮", "Put dirty clothes in the laundry basket", "🧺", 1, false, false, true, null, 23),
        Item("seed-task-floss", "用牙线", "Floss my teeth", "🦷", 2, false, false, true, "floss_pick", 24),
        Item("seed-task-evening-brush", "晚上刷牙", "Brush my teeth at night", "🪥", 2, false, true, true, null, 25),
        Item("seed-task-reading", "阅读或一起读书", "Read on my own or together", "📚", 3, false, true, true, null, 26),
        Item("seed-task-bedtime", "按约定时间上床", "Go to bed at the agreed time", "🛌", 2, false, true, true, null, 27),
        Item("reward-sticker", "选一张贴纸", "Choose a sticker", "⭐", 5, true, true, true, null, 28),
        Item("reward-family-game", "决定下一次家庭游戏玩什么", "Choose the next family game", "🎲", 10, true, true, true, null, 29),
        Item("reward-craft", "选择一次手工活动", "Choose a craft activity", "🎨", 10, true, true, true, null, 30),
        Item("reward-weekend-activity", "选择周末的一项活动", "Choose a weekend activity", "🌳", 20, true, true, true, null, 31),
        Item("reward-family-movie", "选一部家庭电影", "Choose a family movie", "🎬", 20, true, false, true, null, 32),
        Item("reward-video", "看视频 15 分钟", "15 minutes of videos", "📺", 15, true, false, true, "reward_tv_transparent", 33),
        Item("reward-game", "电子游戏 15 分钟", "15 minutes of video games", "🎮", 15, true, false, true, null, 34),
        Item("reward-book", "选一本新书", "Choose a new book", "📖", 30, true, false, true, null, 35),
        Item("reward-small-gift", "选一份约定预算内的小礼物", "Choose a small gift within the agreed budget", "🎁", 40, true, false, true, null, 36),
        Item("reward-outing", "安排一次特别出游", "Plan a special outing", "🎡", 60, true, false, true, null, 37),
    )
}
